DEFAULT_BOSS_TURNS = 2
DEFAULT_BOSS_HP_MULT = 6.0
DEFAULT_BOSS_DAMAGE_MULT = 1.0
AVATAR_OVERKILL_RESISTANCE = 0.75
AVATAR_DILUTED_STATUS_CONDITIONS = false
AVATAR_DILUTED_EFFECTIVENESS = false
AVATAR_DILUTED_STAT_STEPS = false
PRIMEVAL_MOVES_RESET_DEBUFFS = true

AVATARS_REGULAR_ATTACKS_PIERCE_PROTECT = false
AVATARS_REGULAR_ATTACKS_PIERCE_IMMUNITIES = false
AVATARS_TELEGRAPH_REGULAR_ATTACKS = true
AVATARS_FEAR_NOT_FAINT = false
HEALING_RATIO_ON_FEAR_REMOVED = 0

# Avatar AI
AVATARS_RANDOMLY_PRIORITIZE_FAINTING = false
AVATARS_DIVERSIFY_TARGETING_BETWEEN_ROUNDS = true
AVATARS_PREFER_OTHER_SLOT_BETWEEN_TURNS = true
AVATARS_DISLIKE_REPEATING_SAME_MOVE = true
AVATARS_START_WITH_STAB = false
AVATARS_PRIORITIZE_SAME_TURN_TARGETS = true
AVATARS_CANT_CHANGE_TARGETING = false
AVATARS_CALCULATE_DAMAGE_DEALT = false
AVATAR_DAMAGE_SCORE_MAX = 100