CLOTHING_ITEMS =
	[:ROCKYHELMET,:CHOICEBAND,:CHOICESCARF,:CHOICESPECS,:BINDINGBAND,
		:EXPERTBELT,:MUSCLEBAND,:WISEGLASSES,:FOCUSBAND,:FOCUSSASH,:MACHOBRACE,
		:POWERWEIGHT,:POWERBRACER,:POWERBELT,:POWERLENS,:POWERBAND,:POWERANKLET,
		:BLACKBELT,:BLACKGLASSES,:SILKSCARF,:REDSCARF,:BLUESCARF,:YELLOWSCARF,
		:PINKSCARF,:GREENSCARF,:SACHET,:EJECTPACK,:HEAVYDUTYBOOTS,:UTILITYUMBRELLA,
		:GALARICACUFF,:GALARICAWREATH,:ALOLANWREATH,:ASSAULTVEST,:STRIKEVEST
	]