CLOTHING_ITEMS =
	[:ROCKYHELMET,:BUSTEDRADIO,:CHOICEBAND,:CHOICESCARF,:CHOICESPECS,:BINDINGBAND,
		:EXPERTBELT,:MUSCLEBAND,:WISEGLASSES,:FOCUSBAND,:FOCUSSASH,:MACHOBRACE,
		:POWERWEIGHT,:POWERBRACER,:POWERBELT,:POWERLENS,:POWERBAND,:POWERANKLET,
		:BLACKBELT,:BLACKGLASSES,:SILKSCARF,:REDSCARF,:BLUESCARF,:YELLOWSCARF,
		:PINKSCARF,:GREENSCARF,:SACHET,:EJECTPACK,:HEAVYDUTYBOOTS,:UTILITYUMBRELLA,
		:GALARICACUFF,:GALARICAWREATH,:ALOLANWREATH,:ASSAULTVEST,:STRIKEVEST,

		# Super items
		:CHOICECROWN, :ZENITHBAND, :ZENITHSPECS, :ZENITHSCARF,
		:CLARITYSASH, :ALLPURPOSEVEST, :JAGGEDHELMET, :RUPTUREDRADIO, :ASSAULTCORSET, :STRIKECORSET
	]

CHOICE_LOCKING_ITEMS = [:CHOICEBAND,:CHOICESPECS,:CHOICESCARF, :CHOICECROWN, :ZENITHBAND, :ZENITHSPECS, :ZENITHSCARF]
STATUS_PREVENTING_ITEMS = [:ASSAULTVEST,:STRIKEVEST,:ALLPURPOSEVEST,:ASSAULTCORSET,:STRIKECORSET]

SUPER_ITEMS = [
	# Clothing
	:CHOICECROWN, :ZENITHBAND, :ZENITHSPECS, :ZENITHSCARF,
	:CLARITYSASH, :ALLPURPOSEVEST, :JAGGEDHELMET, :RUPTUREDRADIO, :ASSAULTCORSET, :STRIKECORSET,
	# Berries
	:SITREONBERRY, :ROSELIFEAST,:RINDOFEAST, :OCCAFEAST, :LUNUSBERRY, :ZALAKABERRY
	# Rings are pushed to this elsewhere
]