CLOTHING_ITEMS =
    [:ROCKYHELMET, :HIVISJACKET, :CHOICEBAND, :CHOICESCARF, :CHOICESPECS, :BINDINGBAND,
     :EXPERTBELT, :MUSCLEBAND, :WISEGLASSES, :FOCUSBAND, :FOCUSSASH, :MACHOBRACE,
     :POWERWEIGHT, :POWERBRACER, :POWERBELT, :POWERLENS, :POWERBAND, :POWERANKLET,
     :BLACKBELT, :BLACKGLASSES, :SILKSCARF, :REDSCARF, :BLUESCARF, :YELLOWSCARF,
     :PINKSCARF, :GREENSCARF, :SACHET, :EJECTPACK, :HEAVYDUTYBOOTS, :UTILITYUMBRELLA,
     :GALARICACUFF, :GALARICAWREATH, :ALOLANWREATH, :ASSAULTVEST, :STRIKEVEST,:SEVENLEAGUEBOOTS,
     :COVERTCLOAK,:NINJASCARF,:KNIGHTHELMET,:DIAMONDTIARA,

     # Super items
     :CHOICECROWN, :ZENITHBAND, :ZENITHSPECS, :ZENITHSCARF,
     :ALLPURPOSEVEST, :JAGGEDHELMET, :LUSTROUSJACKET, :ASSAULTCORSET, :STRIKECORSET,
     :CLARITYSASH, :HEATSASH, :DAMPSASH, :SMOOTHSASH, :ICYSASH,]

CHOICE_LOCKING_ITEMS = %i[CHOICEBAND CHOICESPECS CHOICESCARF CHOICECROWN ZENITHBAND ZENITHSPECS ZENITHSCARF]
STATUS_PREVENTING_ITEMS = %i[ASSAULTVEST STRIKEVEST ALLPURPOSEVEST ASSAULTCORSET STRIKECORSET]
LEVITATION_ITEMS = %i[AIRBALLOON LEADBALLOON]
FULL_ENDURE_ITEMS = %i[FOCUSSASH HEATSASH DAMPSASH SMOOTHSASH ICYSASH]
WEATHER_ROCK_ITEMS = %i[WETROCK HEATROCK SMOOTHROCK ICYROCK PINPOINTROCK MIRROREDROCK]
RECOIL_ITEMS = %i[ROCKYHELMET HIVISJACKET JAGGEDHELMET LUSTROUSJACKET]
HERB_ITEMS = %i[WHITEHERB BLACKHERB POWERHERB ENERGYHERB MENTALHERB MIRRORHERB PARADOXHERB]

SUPER_ITEMS = [
    # Clothing
    :CHOICECROWN, :ZENITHBAND, :ZENITHSPECS, :ZENITHSCARF,
    :ALLPURPOSEVEST, :JAGGEDHELMET, :LUSTROUSJACKET, :ASSAULTCORSET, :STRIKECORSET,
    :CLARITYSASH, :HEATSASH, :DAMPSASH, :SMOOTHSASH, :ICYSASH,

    # Berries
    :SITREONBERRY, :ROSELIFEAST, :RINDOFEAST, :OCCAFEAST, :LUNUSBERRY, :ZALAKABERRY,

    # Rings (are pushed to this from elsewhere)

    # Other
    :WHITEBOUGH, :TERRAINSEALANT, :LEADBALLOON, :SPELLBELL, :HOOHSASHES, :DEATHORB, :GRANDMASTERSCROLL, :LUNCHBOX,
    :POWERKEY, :ENERGYKEY, :BRIGHTCLAY, :PEARLOFFATE
]
