NEW_ABILITIES_STARTING_ID = 268

MOVE_RENAMES =
{
	:CHARM => :POUT,
	:ROCKSMASH => :SMASH,
	:SMARTSTRIKE => :SMARTHORN,
	:SWEETKISS => :ANGELSKISS,
	:DREAMEATER => :DREAMABSORB,
	:TOXICSPIKES => :POISONSPIKES,
	:SUNNYDAY => :SUNSHINE,
	:RAINDANCE => :RAIN,
	:HORNLEECH => :HORNDRAIN,
	:ROLLOUT => :ROCKROLL,
	:ICEBALL => :SNOWBALL,
	:POISONPOWDER => :POISONPOLLEN,
	:STUNSPORE => :PARAPOLLEN,
	:ENERGYBALL => :THRIVINGFORCE,
	:NASTYPLOT => :DREAMDANCE,
	:MIRRORSHOT => :SHINESHOT,
}

ABILITY_RENAMES =
{
	:ADAPTABILITY => :ADAPTED,
	:QUEENLYMAJESTY => :ROYALMAJESTY
}