NEW_ABILITIES_STARTING_ID = 268

MOVE_RENAMES = {
			:CHARM => :POUT,
			:ROCKSMASH => :SMASH,
			:SMARTSTRIKE => :SMARTHORN,
			:SWEETKISS => :ANGELSKISS,
			:DREAMEATER => :DREAMABSORB,
			:TOXICSPIKES => :POISONSPIKES
		}

ABILITY_RENAMES = {
			:ADAPTABILITY => :ADAPTED,
			:QUEENLYMAJESTY => :ROYALMAJESTY
		}

ADDED_TO_EVERYONE = [:MULTISTRIKE]

CUT_FROM_EVERYONE = [:TOXIC,:DOUBLETEAM,:SANDATTACK,:IMPRISON,:FRUSTRATION,:RETURN,:HIDDENPOWER,:ATTRACT]