VOLCANIC_SHORE_VISITED_SWITCH = 326
UNDERGROUND_RIVER_VISITED_SWITCH = 327
TEMPEST_REALM_VISITED_SWITCH = 328
GUARDIAN_ISLAND_VISITED_SWITCH = 329
EVENTIDE_ISLE_VISITED_SWITCH = 330
ISLE_OF_DRAGONS_VISITED_SWITCH = 331
TRI_ISLAND_VISITED_SWITCH = 332
BATTLE_MONUMENT_VISITED_SWITCH = 333
SPIRIT_ATOLL_VISITED_SWITCH = 334

Events.onMapLoadIn += proc { |_sender,_e|
    mapID = $game_map.map_id

    case mapID
    when 193, 196
        setGlobalSwitch(VOLCANIC_SHORE_VISITED_SWITCH)
    when 256, 288, 218
        setGlobalSwitch(UNDERGROUND_RIVER_VISITED_SWITCH)
    when 215
        setGlobalSwitch(TEMPEST_REALM_VISITED_SWITCH)
    when 377, 385..389
        setGlobalSwitch(GUARDIAN_ISLAND_VISITED_SWITCH)
    when 413..414
        setGlobalSwitch(EVENTIDE_ISLE_VISITED_SWITCH)
    when 356
        setGlobalSwitch(ISLE_OF_DRAGONS_VISITED_SWITCH)
    when 411, 415..417
        setGlobalSwitch(TRI_ISLAND_VISITED_SWITCH)
    when 357, 128, 131
        setGlobalSwitch(BATTLE_MONUMENT_VISITED_SWITCH)
    when 182, 375, 419, 420, 421
        setGlobalSwitch(SPIRIT_ATOLL_VISITED_SWITCH)
    end
}